TP1_.NET/Controllers/MoviesMController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TP1_.NET.Models;
using TP1_.NET.Models.DAL;

namespace TP1_.NET.Controllers
{
    public class MoviesMController : Controller
    {
        MovieDbContext db = new MovieDbContext();
        // GET: MoviesM
        public ActionResult Index()
        {
            // Movie m = new Movie() {Title= "The100",Genre ="Aventure",ReleaseDate= new DateTime(2013,10,10),ID=12,Price=22};
            // db.Movies.Add(m);
            // db.SaveChanges();
            return View(db.Movies.ToList());
        }
        public ActionResult Ajouter()
        {
            return View();
        }        
        
        public ActionResult AjouterBase(Movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Movies.Add(movie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View("~/Views/MoviesM/Ajouter.cshtml", movie);
            }
        }
        public ActionResult Modifier(int? id)
        {
            if(id ==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if(movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);

        }



        [HttpPost]
        public ActionResult Modifier(Movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(movie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View("~/Views/MoviesM/Modifier.cshtml", movie);
            }
        }

        public ActionResult Supprimer(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        [HttpPost, ActionName("Supprimer")]
        [ValidateAntiForgeryToken]
        public ActionResult SuppConfirmed(int id)
        {
            Movie movie = db.Movies.Find(id);
            db.Movies.Remove(movie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

TP1_.NET/Views/MoviesM/Ajouter.cshtml
@model  TP1_.NET.Models.Movie

<h2>Ajouter</h2>

@using (Html.BeginForm("AjouterBase", "MoviesM"))
{

    <div class="form-horizontal">
        @Html.ValidationSummary()
        @Html.LabelFor(model => model.Title)
        @Html.EditorFor(model => model.Title)
        @Html.ValidationMessageFor(model => model.Title)
        <br />

        @Html.LabelFor(model => model.ReleaseDate)
        @Html.EditorFor(model => model.ReleaseDate)
        @Html.ValidationMessageFor(model => model.ReleaseDate)
        <br />

        @Html.LabelFor(model => model.Genre)
        @Html.EditorFor(model => model.Genre)
        @Html.ValidationMessageFor(model => model.Genre)
        <br />

        @Html.LabelFor(model => model.Price)
        @Html.EditorFor(model => model.Price)
        @Html.ValidationMessageFor(model => model.Genre)
        <br />
        <input type="submit" value="Ajouter" />
    </div>
}
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

TP1_.NET/Views/MoviesM/Index.cshtml
@model  IEnumerable<TP1_.NET.Models.Movie>

<h2>Index</h2>


@Html.ActionLink("Nouveau Film","Ajouter")

<table class="table">
    <thead  class="thead-dark">
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(x => x.Title)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(x => x.ReleaseDate)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(x => x.Genre)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(x => x.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr scope="row">
                <td>
                    @Html.DisplayFor(x => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(x => item.ReleaseDate)
                </td>
                <td>
                    @Html.DisplayFor(x => item.Genre)
                </td>
                <td>
                    @Html.DisplayFor(x => item.Price)
                </td>
                <td>
                    @Html.ActionLink("Modifier","Modifier",new { id = item.ID })|
                    @Html.ActionLink("Supprimer", "Supprimer", new { id = item.ID })|
                    @Html.ActionLink("Détail","Detail",new { id = item.ID })|
                </td>


            </tr>
        }

    </tbody>
</table>

TP1_.NET/Views/MoviesM/Modifier.cshtml
@model  TP1_.NET.Models.Movie

<h2>Modifier</h2>

@using (Html.BeginForm("Modifier", "MoviesM"))
{

    <div class="form-horizontal">
        <div class="form-group">

            @Html.ValidationSummary()
            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, " ", new { @class = "text-danger" })
                </div>




                @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReleaseDate, " ", new { @class = "text-danger" })
                </div>

                @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Genre, " ", new { @class = "text-danger" })
                </div>

                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, " ", new { @class = "text-danger" })
                </div>

                <input type="submit" class="btn btn-success" value="Modifier" />
            </div>
        </div>
</div>
                }
                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }

TP1_.NET/Views/MoviesM/Supprimer.cshtml
@model TP1_.NET.Models.Movie

@{
    ViewBag.Title = "Supprimer";
}

<h2>Supprimer</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>